# Usa la imagen oficial de Prometheus
FROM prom/prometheus:latest

# Copia tu archivo de configuración de Prometheus al contenedor
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Exponer el puerto de Prometheus
EXPOSE 9090